### PR TITLE
Implement a new `use` syntax

### LINKED ISSUE #378: [witx] Make `use` import individual names from other modules
Witx's current mechanism for supporting declarations across multiple files is `use` which imports the contents of one file into another. This was a simple way to get witx started, however it isn't amenable to splitting up WASI into multiple modules.

A better approach would be to have `use` work more like a proper module system in high-level programming languages, where one can `use` specific items from other modules.

So instead of
```wasm
(use "typenames.witx")
```

We should have something like
```wasm
(use $timestamp from $wasi_filesystem)
```
where `$wasi_filesystem is a module which defines a `$timestamp` type.

### LINKED ISSUE #379: [witx] Update witx parser for new `use` syntax
We'll be defining a new `use` syntax in #378. 

We'll need to update the .witx parser to parse this new syntax.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit implements a new `use` syntax which changes

    (use "foo.witx")

to

    (use $some $type $names from $foo)

This change ended up being much larger than originally intended. While
at a surface level switching this style of `use` statements isn't too
bad it has large ramifications on the mental model of how to interpret
and work with `*.witx` files. This necessitated some internal
refactorings which ended up as a bit of a yak shave. The other changes
here are:

* The `polyfill` module is removed. I confirmed with Pat that this isn't
  used anymore and this came about trying to update it from the below
  refactorings.
* The `render` module is removed. Documents can no longer be serialized
  to a standalone s-expression because they can refer to other documents
  in a structured manner. It's also believed there are no current users
  of this functionality.
* The `representation` module was removed since it was largely only used
  by the `polyfill` module.
* The `Document` type was renamed to `Module`, and the ability for a
  document to contain multiple modules has been removed. When working
  with multiple modules this must now be done so explicitly instead of
  having it all lumped into one parsed object. This means that
  `Module` is now a list of types and a list of functions.
* Documentation has changed to document a set of modules instead of a
  single module. Additionally this is nontrivially changed to load types
  transitively from all modules referenced to ensure that all relevant
  types are documented.
* Internal refactorings in the validation phase have been done to
  streamline a few things and consolidate where possible with this new
  structuring.
* `InterfaceFunc` is now named `Function`
* `InterfaceFuncParam` is now named `Param`
* `Module` has a `name` (as before) which is now inferred from the
  filename it's loaded from.
* `Module` has a `ModuleId` now to represent types that are defined in
  other modules, where `ModuleId` is intended to be a unique identifier
  amongst a set of modules. For now it's just a path name but can likely
  get more fancy in the future if needed.

All `*.witx` files have been updated to the new syntax in this
repository. Lots of changes look like they happened to the proposal
documentation, but that's just because the documentation order of types
has been shuffled around. I've checked to make sure no actual items were
lost from the documentation.

Closes #378
Closes #379

### CODE REVIEW

**Comment by devsnek** [comment]
feel free to ignore, but it would be nice if something delineated the list of import names. maybe an extra pair of parens?

**Comment by sunfishcode** [comment]
Overall this looks good! My biggest concern here is the removal of the top-level `(module` `)` syntax. For what it's worth I proposed a simlar syntax change back when the original wat syntax was being designed and it was clear that we wanted a file format fold holding exactly-one-module. But now, with witx being derived from wat syntax, and wat syntax retaining the outer `(module` `)` around it, it feels like witx should retain it too.

**Comment by sbc100** [comment]
Isn't the outer `(module ..)` syntax optional in the `.wit` format?

**Comment by alexcrichton** [comment]
I am not personally wed to any particular syntax here, so I'm happy to tweak as necessary for imports/etc.

@sunfishcode are you ok with the one-module-per-text-file restriction? (same as `*.wat`) It sounds like the `module` wrapper would be purely syntactical but wanted to confirm.

It's also true yeah that at least in `*.wat` the `(module ...)` is optional but AFAIK almost no one omits it, so seems reasonable to start requiring `(module` here and it can always be relaxed in the future.

**Comment by sunfishcode** [comment]
One-module-per-file is ok with me. Hmm, I actually forgot that `(module ...)` is optional; it's not optional in [the spec](https://webassembly.github.io/spec/core/text/modules.html#text-module), and all the official examples include it, and it does seem everyone use it includes it in practice.

I think my instinct is that we should support and require the `(module ...)` at this point, though I could be convinced otherwise.

**Comment by alexcrichton** [comment]
Ok updated!

**Review by sunfishcode — APPROVED** [review]

**Pull request merged**
