### PR TITLE
Initial checkin of test scripts, copied from wasi-sdk.

### PR DESCRIPTION
**Pull request by sunfishcode**
This just copies in the test scripts from https://github.com/WebAssembly/wasi-sdk/tree/main/tests. We can evolve them from this point on.

### CODE REVIEW

**Comment by sunfishcode** [comment]
This is a first draft at a concrete setup for the testing process described in #373. I copied in the same test script that #373 describes and set up a basic directory structure, which hopefully makes it clear where things will go in the repository.

**Comment by caspervonb** [comment]
Got some things I want to change here but I'll follow up with that.

LGTM, good to get the ball finally rolling on this.

**Comment by sbc100** [comment]
Is the idea that wasi-sdk will then get its test runner from the WASI submodule (and we can then delete its copy).?

**Comment by sunfishcode** [comment]
The wasi-sdk version of these scripts has support for running the tests with different optimization levels, and also compile-only tests, but I think what we can do is build those on top of the scripts here.

**Comment by sunfishcode** [comment]
I'm going to take the liberty of merging this, so we can proceed to iterate on top of it. If there are further comments, please file issues in the issue tracker!

**Pull request merged**
