### PR TITLE
Add the slides for the Typed Main presentation.

### PR DESCRIPTION
**Pull request by sunfishcode**

### CODE REVIEW

**Comment by kripken** [comment]
Would it be possible to also attach a rendering (say, PDF) of the slides? In this PR I'm not sure how to view them without downloading the repo and starting up a webserver.

**Comment by sbc100** [comment]
Or maybe just link to the online version?

**Comment by sunfishcode** [comment]
The online version is [here](https://sunfishcode.github.io/typed-main-wasi-presentation/) for now.

**Comment by kripken** [comment]
Thanks!

**Pull request merged**
