### PR TITLE
Fixed typo in random_get documentation

### PR DESCRIPTION
**Pull request by guyroyse**

### CODE REVIEW

**Comment by jedisct1** [comment]
Good catch!

The markdown files are automatically generated from the `witx` files. So, the change should be made there.

**Comment by guyroyse** [comment]
The typo is in two of the witx files that I can see, the ephemeral and the snapshot. I'll send an updated PR.

**Comment by sunfishcode** [comment]
Thanks for reporting this! It's admittedly a little confusing because we're in the middle of a transition away from having everything in this repo towards having proposal repos, with the random APIs in WebAssembly/wasi-random. I've now created WebAssembly/wasi-random#4 to port this fix to the wasi-random repository (and added you in the Co-authored-by).

**Comment by guyroyse** [comment]
Thanks! I shall close this PR then.

**Pull request closed without merging**
